const Home = () => {
  return (
    <div>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
      <h1>Stories</h1>
      <h1>CreateNewPost</h1>
      <h1>Sort</h1>
      <h1>NewsFeed</h1>
    </div>
  )
}

export default Home
